language: generic
services:
- docker
before_install:
- docker build -t jc1204/odoo-13-gcsfuse .
deploy:
  provider: script
  script:
  - docker login -u ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD} && docker push jc1204/odoo-13-gcsfuse
  on:
    branch: master
env:
  global:
  # - secure: dsq+XHwCa7OuPjHHp6UNM0WxIj/8cskZ7rr7q9TxTi68paK6QtqpyM6adanr5zEpgTd9KwnJ/h+kPI/v1dH7EG3fC/K0/2XZpJwm0NKwCo4H++OjOTjY9HhYiPIc4M0scneMibAQWoKR5naIe77riRDZPrOjzEm+Lna0EyVurX6c/GbnubecsRCfPYehWkXrGeepNUt50wFlswEaM6kbfLjad+o6HTv39mjw4zJ6beBCkHlEvkTEOThitSzixz/tD1XomAZWWaey1LlvfNzOI2x1auJxIzO2l0v+xgX7Ip8ODhRMnbKxGhNn9byCQbBynRUtr3CFSqF7Xt5tUmFL3Tcf3bqit81Ku63ZebjE7d8kdx8Y/mETbE4jLOE5tmn6q/NlVGEo3LDkKKJyf9EQC5/f6Wezu9gAmpWoxHMfsXg+UNWjmsGzVAPLiDrd18iIYzvkDiO+oj2A2gnpz5r53PdcbSx4nhvjE7wEgpgyJRuJphgYi4+wu9A6/PPlOwiynreNJNfUsnjs9BTONGcP6RrdYYvgxH+vyJUO+zQ23PC0l3XcaTJ5wjL7MEvqc3rslQP/J5x97RXkp8QyNby81slcUt5zbzcQmCucTqcX0zyHAdBNQR4wCHY0E67iVBdKECHcJlEBS+o9KKU+U/qsd5VXACCxmM+8m6MA5SXRwkw=
  # - secure: WpsxmlSJo55Q37nzydNnGZ22T9aHR3nqddTnd6uEoj+cJqoj7qXOMKRupiTyyRgyvSjmZKkaNoN5T5oaN+h/CKUKfbiVzBoXr6/4u2QpQ42FkvkXLO5/9GqlU6EZYb7QpIefnUQ1BbOOoiqYNTcSVawuXrXAkXOOFWt+tIa7NODO8CjqmIY99006jhPnQvBEsEuq66BUZhyXM39dgt50HkqC58gEggppEO8Z1jQWgdEos5BEop3PWqT3aa9+5w2ZW8stne3QCMzDwDUOAB5pg3KH/3iypqoGLcfy4ppotsL4Bfmhs1Din0GzJ4J3hD22cfJS3l+2mMhgUyGa7dN/Oor54Xv66prX2Tlr7cWQuy8hJ7x9Ti4YQMaMKhvi8nF71uzRy911imYz7+1B799tk22Sag/1pVTeFmT0Ut+NeUacPl++Wg/PTXR+EdqgWgGYoNNeNi+P0xBazm8oDphWEXLUFytjJn/oEJIUI8h3WNcuHP9lGESmDabE3CDqulR1jCz5nqN3WCDuHSNF2lwq79i6wv/sCBeTTtNrnqHHTk/MfXiCpjqAe+dJZGz0LGBtnmYb11CkH+ShC1RL24gj3LCTXiDi3Ti67bHVle45oktSSblIk1Ci2f1lPW9MCAc6L2BtQZMOp5YFIBmiBXgtkkkUKRsShmCaslsu9EWiQWA=
