language: python
services:
- docker
before_install: 
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  on:
    branch: master
env:
  global:
  # - secure: EmSWhnRkXXae8lJubaSK7ZUyXoGwPVXL16juuMp5C8FyBBDWaxLmMZ5pM6xDAcEMoFq5zRsHSLnHV6qBprqFiaOdknECdru3w5dGFBjwF9bY++DU1hMp0oZRr6/DFy7hJKLWWQvbizGwM2swdpj+7Thyt6yOVHopkF6vdKgoqtbPHq+o/dPbdGOshFDY7wf717mVKc39DqEiz+j9zAuZ3EZYmUWyBx72bowmoEWB6s+uLZhMc4X1d5RkScy7yuHt9KgGZBVADuOIzNdrTjeXLhEpyB34edtX+ctCW3buzWcbP3Vr8MYifEsCWKW3gAQLc8lWDvPS79yJG3IY1MfVhjIE3TokbJS0BrHDFCNSDK4k/R75gtUNJJ2TFmVsO9z47hNY6FD/9e+pF8wg+0s6RRn8Y0soahrgBHKwuyFSOuVcpBce1nNQP8TpULdLYWiB5WT+NeJf3aChjWX/q2DcnIWL6pECXWNl++Ojs1E+uPZOYhznJgGsw0bVAnnKIzVI+A4McONPa9Oh+rL/mRGF4Mk8jkZz3wx/gDGQQmAv0Q0gqZ0UK7zOGPmQq4eK2kgZEUeXoUQvGq8LxWLWPf5++1vhXskeSxyxgfIHO2JFMGkLZGFc+7+/AsNvstK5n2AVPi+2SkcSFTVH1VIG6dmyDETH1hONcUxyex9+WiYGh8c=
  # - secure: w6/YptYDeo6UFHpzaeITGDT2qr01pM0OJPm0eYECEAAsRpkPBhB5pGgTc/BKbz+R0H1CMyz426dIe9Oyz2BqZvAxT0XZyOQr8wejR3JU20nNHPkv6xdiKH5hN9EhrL/tFejZcRePxUnJpU3oCkZI0fsM8yd0m/dOmxWvfFxbeBZ17IFux0s+cE+52/6ZUdmaGVFkkNrZ6mBTouI9Mx8Et5meGedQq+81ieUw8WT85gsK04oKsWiFSClV0fwdmHDiUs/Ztjw1sZgsqmskLWFfVYGCDLzE5Pb2M6nNNnjQsskkRcAh1G+BMqXY9SzMdtO8/JXLwATwu/JtifQZ5rQxwSEODJsyYKEY/8Mj7dJoQ6I5AcE34JnGL3Ydul5/VsxDgEAjBJsvdQZ/iZowAi81cpbEd9ya/UAEHE7XlCCJr2hkzxh/5AP21iCmajx7DD626QO2a0TW1fqGzKhJPTc6Pv4fPB/jkG/ryoNoWqs2tiUOmU5Gz4YDEYzFSBTrabZKJ1Wb28Lujl9GXsUJg0+GZTvVDqi8U4Q9Wb+G44ANjbIayHLzKm6uj0v/yaKZBA0aFbSkGXD40cqS2dLNA9eui3Gzt9qQrO5ybL8nU8X5tp1x4k1ondrz0mrpmBe7BrWoYpxpRC7Cp2evuxex/4+Y00MPFbMhawfpHromkGLpEZY=
