language: python

services:
  - docker

before_install:
  - docker build -t jc1204/odoo-13-gcsfuse .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push jc1204/odoo-13-gcsfuse # bash docker_push
  on:
    branch: master
