language: python
services:
- docker
before_install:
- docker build -t jc1204/odoo-13-gcsfuse:$TRAVIS_COMMIT .
- docker tag jc1204/odoo-13-gcsfuse:$TRAVIS_COMMIT jc1204/odoo-13-gcsfuse:latest
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push jc1204/odoo-13-gcsfuse
  on:
    branch: master
env:
  global:
  - secure: O+zQsUhWi4WdvF1hFklO2am0V7l5brPJWYJJNJeDnObxh4CCRCMoSLCFRwJMx9ZuhHMyAs7Y0yCeGG0j19CQtJytpWsaNv9ZhZm30PP7Y3crd5cW0ZAwx3v/UngQBT/4bw+2XRUgArl3HWSJtqHdKmqEMZJVB0YAMgDueiqqYjmQ3/63klgwyccjZHe7Fyqi0UshuKXlWfXbwNg1FHqPkKr6cfhpBGHFJgLAT17fzFTii9j4WJkrxOdP0cm/Zc9+snsLUMO+W7ViTLbVGU6RK17+FoJBqjqz4elt+KXk90MN0dZXckmvBX+rM3LP9eJGD/zQyQgLovTYlHIHVqaHHbvEXqi0Szm8nnTvv1/e5kTzEzCMZ1kFbHvvr6lE8pfMkQwaWjY3hLxIuQz2hFTmO4ifKG9Qe90B6Jwyn8R/UtT31Sm/BZyKK5hiZ+aLVcREQFPnlqo03Aiz5vMoO+VKhITJHjHoYj1b5a+eXGmoclWGMXdWClY29yaMWJ0LW/WNMF78XV5H8/oMr76f/7LXifLvPfDcA1zw0jwNHMYPX06Klq1CRHq9Fm8kl8ffKfm0BuGE63InTLGw10YN913Lj2zdPXKoP8T+GPllp5p3pUOhTIArjFlm2agC6hYLPLBVbaN5NEdM3KhPp57i7tTgiSeSWQNf+MsUDd2Yi1hQRYk=
  - secure: Kc5F1dwUAzp7AIcipe8ZoS2n9qFuSBzD9WAkaILfbSBCvVoKsmUKWKxHIAZHQjpjgFQk7gP/w8x364wO72+7lQ6IacebgCxsxKzJ+6RDMXo37IM95WqCoVXyMMb4HJ3CHVz4qjACHmPsCPPTV1EysXBJsDgTnfAgP5ELGw9YHgl/pSayxIw6Tw5Hv2OfL2sAVO/Gv418LnXbMSz9lFGpUpDoWm8q1SHyx+VmwNDbI31hhQeRow/1m69m5FRhV00WDm4YOPsRfM1gwLvDBoPGBZ+ltP1m6SUXXMhD3D1maplmo6NRdJoCqwTjUMVixpwHqIb69wO7Oeyg1iJqnHo2eh/y649X4wg3VH1Qaz4wgiBVyN3OMRkuL/L5dAe1Xftf9MG19jMbZCAbQuAlST0850OCUea+iKP5RPoohhQFXKF2marA6OJ2GPFPCfcddzk9JzMDEIe0NKhI+vXWLyQ6uDb+ZKw6GsXS0w+gjJHQEt/MpSPcW+2qd6D5pF4Oh7imI521hiXaKepR0JVFM5Kf5Idoq9JW78dPpws1oyvszAt4M/nNf0t1olvYHa7M4ZlyjXDASi1bDY55p30YtMVTyudRcoLAUIWz/OxbxcSy29qaYqXPhmgXjayvn9ANNvTovV7igZh/FCT6dTHrbsygd/Pwx7HIxLG22rn/RKcsb5E=
