language: python
services:
- docker
before_install:
#  install kubectl
#  get cluster credentials
- export IMAGE_TAG="$(git log -1 --pretty=%h)"
- docker build -t jc1204/odoo-13-gcsfuse:$IMAGE_TAG .
#- docker tag jc1204/odoo-13-gcsfuse:$TRAVIS_COMMIT jc1204/odoo-13-gcsfuse:latest
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push jc1204/odoo-13-gcsfuse
  on:
    branch: master

## script
# kubectl set image deployment/odoo odoo=jc1204/odoo-13-gcsfuse:21fc79e --record
